name: AgentPager
options:
  bundleIdPrefix: com.agentpager
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: AgentPager/Info.plist
    DEVELOPMENT_TEAM: "MB75Y85CCZ"

targets:
  AgentPager:
    type: application
    platform: iOS
    sources:
      - path: AgentPager
        excludes:
          - "project.yml"
          - "*.xcodeproj"
    entitlements:
      path: AgentPager/AgentPager.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpager.ios
        INFOPLIST_FILE: AgentPager/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        CODE_SIGN_ENTITLEMENTS: AgentPager/AgentPager.entitlements
