// Constants
export {
  PROTOCOL_VERSION,
  DEFAULT_HOOK_HTTP_PORT,
  DEFAULT_WS_PORT,
  GATEWAY_SOCK,
  HOOK_SOCK,
  SESSION_STATUSES,
  RISK_LEVELS,
  APPROVAL_SCOPES,
  AGENT_NAMES,
  TMUX_PREFIXES,
  HEARTBEAT_INTERVAL_MS,
  HEARTBEAT_TIMEOUT_MS,
  MAX_MISSED_HEARTBEATS,
  RECONNECT_BASE_MS,
  RECONNECT_MAX_MS,
  EVENT_BUFFER_SIZE,
  MAX_DIFF_BYTES,
  FRAME_INTERVAL_MS,
  HIGH_WATERMARK,
  LOW_WATERMARK,
  SCROLLBACK_LINES,
  APPROVAL_TIMEOUT_MS,
  DANGEROUS_DELAY_MS,
  TOTP_MAX_ATTEMPTS,
  TOTP_WINDOW_MS,
  TOTP_CODE_EXPIRY_S,
  READ_ONLY_TOOLS,
  DEFAULT_RELAY_URL,
  RELAY_RECONNECT_BASE_MS,
  RELAY_RECONNECT_MAX_MS,
} from "./constants.js";

// Envelope
export {
  MessageEnvelopeSchema,
  createEnvelope,
  type MessageEnvelope,
} from "./envelope.js";

// Events (Gateway → Client)
export {
  RiskLevelSchema,
  SessionStatusSchema,
  DiffHunkSchema,
  DiffPayloadSchema,
  SessionStartPayloadSchema,
  SessionEndPayloadSchema,
  SessionUpdatePayloadSchema,
  PermissionRequestPayloadSchema,
  ToolCompletePayloadSchema,
  MessagePayloadSchema,
  ProgressPayloadSchema,
  ErrorPayloadSchema,
  HeartbeatPayloadSchema,
  SessionInfoSchema,
  SessionListPayloadSchema,
  SessionSnapshotPayloadSchema,
  EVENT_TYPES,
  EVENT_PAYLOAD_SCHEMAS,
  type RiskLevel,
  type SessionStatus,
  type DiffHunk,
  type DiffPayload,
  type SessionStartPayload,
  type SessionEndPayload,
  type SessionUpdatePayload,
  type PermissionRequestPayload,
  type ToolCompletePayload,
  type MessagePayload,
  type ProgressPayload,
  type ErrorPayload,
  type HeartbeatPayload,
  type SessionInfo,
  type SessionListPayload,
  type SessionSnapshotPayload,
  type EventType,
  AuthRequiredPayloadSchema,
  type AuthRequiredPayload,
} from "./events.js";

// Actions (Client → Gateway)
export {
  ApproveActionSchema,
  DenyActionSchema,
  EditApproveActionSchema,
  TextInputActionSchema,
  StopActionSchema,
  PauseActionSchema,
  StartSessionActionSchema,
  TerminalInputActionSchema,
  BatchApproveActionSchema,
  ResumeFromSeqActionSchema,
  AuthActionSchema,
  ACTION_TYPES,
  ACTION_PAYLOAD_SCHEMAS,
  type ApproveAction,
  type DenyAction,
  type EditApproveAction,
  type TextInputAction,
  type StopAction,
  type PauseAction,
  type StartSessionAction,
  type TerminalInputAction,
  type BatchApproveAction,
  type ResumeFromSeqAction,
  type AuthAction,
  DevicePairActionSchema,
  type DevicePairAction,
  type ActionType,
} from "./actions.js";

// Risk classification
export {
  classifyRisk,
  summarizeTool,
  extractTarget,
  categorrizeTool,
} from "./risk.js";
