#!/usr/bin/env bash
set -euo pipefail

# AgentPager Setup Wizard
# Generates config, deploys hook scripts, sets up auto-start

AGENTPAGER_DIR="$HOME/.agentpager"
CONFIG_FILE="$AGENTPAGER_DIR/config.toml"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}AgentPager Setup Wizard${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Check prerequisites ──────────────────────────────────────────────

check_prereq() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}✗ $1 not found${NC}"
    return 1
  fi
  echo -e "${GREEN}✓ $1 found${NC}"
  return 0
}

echo "Checking prerequisites..."
check_prereq bun || { echo -e "${RED}Install Bun: curl -fsSL https://bun.sh/install | bash${NC}"; exit 1; }
check_prereq tmux || echo -e "${YELLOW}⚠ tmux not found — terminal streaming will be limited${NC}"

# Check for supported agents
echo ""
echo "Detecting agents..."
AGENTS_FOUND=0
if command -v claude &>/dev/null; then
  CLAUDE_VERSION=$(claude --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo "unknown")
  echo -e "${GREEN}✓ Claude Code v${CLAUDE_VERSION}${NC}"
  AGENTS_FOUND=$((AGENTS_FOUND + 1))
fi
if command -v codex &>/dev/null; then
  CODEX_VERSION=$(codex --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo "unknown")
  echo -e "${GREEN}✓ Codex CLI v${CODEX_VERSION}${NC}"
  AGENTS_FOUND=$((AGENTS_FOUND + 1))
fi
if command -v gemini &>/dev/null; then
  echo -e "${GREEN}✓ Gemini CLI${NC}"
  AGENTS_FOUND=$((AGENTS_FOUND + 1))
fi

if [ "$AGENTS_FOUND" -eq 0 ]; then
  echo -e "${YELLOW}⚠ No supported agents found. AgentPager will still work with manual hook setup.${NC}"
fi
echo ""

# ── Create data directory ────────────────────────────────────────────

echo "Setting up data directory..."
mkdir -p "$AGENTPAGER_DIR"
chmod 700 "$AGENTPAGER_DIR"
echo -e "${GREEN}✓ $AGENTPAGER_DIR${NC}"

# ── Generate config ──────────────────────────────────────────────────

if [ -f "$CONFIG_FILE" ]; then
  echo -e "${YELLOW}Config already exists at $CONFIG_FILE${NC}"
  read -rp "Overwrite? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Keeping existing config."
  else
    generate_config=true
  fi
else
  generate_config=true
fi

if [ "${generate_config:-false}" = true ]; then
  # Generate secure token
  TOKEN=$(openssl rand -base64 32 | tr -d '=' | tr '+/' '-_')

  cat > "$CONFIG_FILE" <<EOF
# AgentPager Gateway Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Auth token for hook HTTP endpoint (required)
hook_token = "$TOKEN"

# HTTP port for hook ingestion (backward compat with Agent Pager)
hook_http_port = 7890

# WebSocket port for client connections
ws_port = 7891

# Log level: debug, info, warn, error
log_level = "info"

# Auto-approve safe tool invocations (Read, Glob, Grep, etc.)
auto_approve_safe = false
EOF

  chmod 600 "$CONFIG_FILE"
  echo -e "${GREEN}✓ Config generated at $CONFIG_FILE${NC}"
  echo -e "  Hook token: ${YELLOW}${TOKEN:0:8}...${NC} (full token in config file)"
fi

# ── Deploy hook scripts ──────────────────────────────────────────────

echo ""
echo "Deploying hook scripts..."

deploy_claude_hooks() {
  local hooks_dir="$HOME/.claude/hooks"
  mkdir -p "$hooks_dir"

  # Create Claude Code hooks configuration
  local settings_file="$HOME/.claude/settings.json"

  echo -e "${GREEN}✓ Claude Code hook scripts ready at $SCRIPT_DIR/hooks/claude/${NC}"
  echo ""
  echo -e "${YELLOW}To enable hooks, add the following to your Claude Code settings:${NC}"
  echo -e "${YELLOW}  File: ~/.claude/settings.json${NC}"
  echo ""
  echo '  {'
  echo '    "hooks": {'
  echo '      "PreToolUse": ['
  echo "        { \"matcher\": \"*\", \"hooks\": [\"bun $SCRIPT_DIR/hooks/claude/pre-tool-use.ts\"] }"
  echo '      ],'
  echo '      "Notification": ['
  echo "        { \"matcher\": \"*\", \"hooks\": [\"bun $SCRIPT_DIR/hooks/claude/notification.ts\"] }"
  echo '      ],'
  echo '      "Stop": ['
  echo "        { \"matcher\": \"*\", \"hooks\": [\"bun $SCRIPT_DIR/hooks/claude/stop.ts\"] }"
  echo '      ]'
  echo '    }'
  echo '  }'
}

deploy_codex_hooks() {
  echo -e "${GREEN}✓ Codex CLI hook scripts ready at $SCRIPT_DIR/hooks/codex/${NC}"
  echo ""
  echo -e "${YELLOW}To enable hooks for Codex CLI, configure the before-tool hook.${NC}"
}

if command -v claude &>/dev/null; then
  deploy_claude_hooks
fi
if command -v codex &>/dev/null; then
  deploy_codex_hooks
fi

# ── Auto-start (launchd on macOS, systemd on Linux) ─────────────────

echo ""
echo "Auto-start configuration..."

setup_launchd() {
  local plist_path="$HOME/Library/LaunchAgents/com.agentpager.gateway.plist"
  local bun_path=$(which bun)

  cat > "$plist_path" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.agentpager.gateway</string>
  <key>ProgramArguments</key>
  <array>
    <string>$bun_path</string>
    <string>run</string>
    <string>$SCRIPT_DIR/src/index.ts</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$AGENTPAGER_DIR/gateway.log</string>
  <key>StandardErrorPath</key>
  <string>$AGENTPAGER_DIR/gateway.error.log</string>
  <key>WorkingDirectory</key>
  <string>$SCRIPT_DIR</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:$HOME/.bun/bin</string>
  </dict>
</dict>
</plist>
EOF

  echo -e "${GREEN}✓ launchd plist created at $plist_path${NC}"
  echo ""
  read -rp "Load the service now? [Y/n] " load_now
  if [[ ! "$load_now" =~ ^[Nn]$ ]]; then
    launchctl load "$plist_path" 2>/dev/null || true
    echo -e "${GREEN}✓ Gateway service loaded${NC}"
  fi
}

setup_systemd() {
  local service_path="$HOME/.config/systemd/user/agentpager-gateway.service"
  local bun_path=$(which bun)
  mkdir -p "$(dirname "$service_path")"

  cat > "$service_path" <<EOF
[Unit]
Description=AgentPager Gateway Daemon
After=network.target

[Service]
Type=simple
ExecStart=$bun_path run $SCRIPT_DIR/src/index.ts
WorkingDirectory=$SCRIPT_DIR
Restart=on-failure
RestartSec=5
StandardOutput=append:$AGENTPAGER_DIR/gateway.log
StandardError=append:$AGENTPAGER_DIR/gateway.error.log

[Install]
WantedBy=default.target
EOF

  echo -e "${GREEN}✓ systemd service created at $service_path${NC}"
  echo ""
  read -rp "Enable and start the service now? [Y/n] " start_now
  if [[ ! "$start_now" =~ ^[Nn]$ ]]; then
    systemctl --user daemon-reload
    systemctl --user enable agentpager-gateway
    systemctl --user start agentpager-gateway
    echo -e "${GREEN}✓ Gateway service started${NC}"
  fi
}

case "$(uname -s)" in
  Darwin)
    setup_launchd
    ;;
  Linux)
    if command -v systemctl &>/dev/null; then
      setup_systemd
    else
      echo -e "${YELLOW}⚠ No supported init system found. Start manually: bun run $SCRIPT_DIR/src/index.ts${NC}"
    fi
    ;;
  *)
    echo -e "${YELLOW}⚠ Unsupported OS. Start manually: bun run $SCRIPT_DIR/src/index.ts${NC}"
    ;;
esac

# ── Summary ──────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "  Gateway:  bun run $SCRIPT_DIR/src/index.ts"
echo "  Client:   http://localhost:7891"
echo "  Config:   $CONFIG_FILE"
echo "  Logs:     $AGENTPAGER_DIR/gateway.log"
echo ""
echo "Next steps:"
echo "  1. Start the gateway (or it will auto-start on login)"
echo "  2. Configure agent hooks (see above)"
echo "  3. Open http://localhost:7891 on your phone"
echo ""
